### ISSUE TITLE
Articulo => https://developer.mozilla.org/es/Firefox_OS/Screencast_series:_App_Basics_for_Firefox_OS 

### ISSUE THREAD

**Issue by maedca** [mozillahispano/localizacion-mdn#1]

**Comment by rafamagno** [comment]
El artículo está completamente traducido. Voy a realizar una edición final (de lo que yo he hecho) y si hay errores obvios (míos o de otros) los corregiré inmediatamente. Después de eso alguien puede realizar la revisión final.
Si tengo dudas les hare saber a través del foro.
Gracias.

**Comment by ghost** [comment]
Perfecto. Si necesitas cualquier tipo de ayuda, dímelo rafamagno.

**Comment by rafamagno** [comment]
Ya termine con mi revisión y me gusta el producto final. Alguien de mayor jerarquía es libre para realizar la revisión final.

Tienen algún otro artículo que sea prioridad en el que pueda trabajar?

**Comment by maedca** [comment]
Ok gracias voy a realizar la revisión técnica te aviso por acá

**Comment by maedca** [comment]
hola @rafamagno ya revise el artículo y esta genial muchas gracias excelente trabajo
