### ISSUE TITLE
Articulo => https://developer.mozilla.org/es/Marketplace/APIs

### ISSUE THREAD

**Issue by maedca** [mozillahispano/localizacion-mdn#3]

**Comment by rafamagno** [comment]
Listo! Este articulo es corto pero no es secillo.

Maedca, por favor confirmame como traducir: Web APIs y Utility Libraries

**Comment by rafamagno** [comment]
Algun otro articulo pendiente?

**Comment by maedca** [comment]
Si pero en el día creo el otro issue

**Comment by maedca** [comment]
hola @rafamagno doy por cerrado el issue todo bien con el articulo
saludos
