### ISSUE TITLE
Prueba

### ISSUE THREAD

**Issue by hamfree** [mozillahispano/localizacion-mdn#9]
Prueba

**Comment by maedca** [comment]
??

**Comment by hamfree** [comment]
Hola, Manuel.

Por favor, **borra la tarea**. Estaba probando en Waffle.io y me ha permitido generar una tarea (que no debería pues no estoy dado de alta en el proyecto) y luego la he pasado a finalizada. Lo que no deja es colocarlas en las columnas "Pendientes", "En progreso" o "En  revisión".

Por otro lado, quiero colaborar en la traducción del MDN y ya me he puesto en contacto con los que lo llevan ahora en Mozilla-Hispano y me atendré a lo que ellos me digan.

Perdona por la "_intrusión_" en la herramienta. No creía que fuera a dejarme hacerlo. Creo que es un bug de Waffle.io

Un cordial saludo.

**Comment by fjaguero** [comment]
Hola @hamfree,

No es posible borrar la tarea, pero no pasa nada, no te preocupes.

Un saludo.
